### ISSUE TITLE
Creates an empty file called META-INF rather than an empty directory (with gulp-zip >= 1.0)

### ISSUE THREAD

**Issue by Typhlosaurus** [ScottWeinstein/gulp-war#5]
Currently the war contains an entry for META-INF but this creates a zero length file when piped to any recent version of gulp-zip.  It is created by the line:
```
this.emit('data', new File({path: 'META-INF/', contents: new Buffer('')}));
```

gulp-zip currently only creates an empty directory if it is finds a file with `null` contents and `stats.isDirectory() ` returning truthy.  Changing the above line to:

```
this.emit('data', new File({
			path: './META-INF',
			stat: {
				isDirectory: function () {
					return true;
				}
			}
		}));
```

resolves the issue.

N.B. this work with gulp-zip 2.x and 3.x but causes neither a file nor a directory to be created with gulp-zip 1.0.0,

**Comment by ScottWeinstein** [comment]
I'm no longer using the plugin, if you'd like to take over maint, I'll be happy to give you commit access

**Comment by Typhlosaurus** [comment]
Oh, OK.  Sure.  Thanks.

**Comment by Typhlosaurus** [comment]
Should be fixed now.
